apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-archive
spec:
  suspend: true
  schedule: {{ .Values.archiveJob.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: archive
              image: {{ .Values.archiveJob.repository }}:{{ .Values.archiveJob.tag }}
              imagePullPolicy: Always
          restartPolicy: OnFailure