on:
  workflow_dispatch:
  push:
    branches:
      - 'helm'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: kubectl
        uses: azure/setup-kubectl@v3
      - name: helm
        uses: azure/setup-helm@v3
      - name: kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: namespace
        run: kubectl apply -f ./helm/templates/namespace.yaml
      - name: deploy
        run: |
          helm upgrade --install service ./helm \
            --namespace dev --create-namespace \
            --wait