on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        required: false
        description: 'Short SHA of commit to be deployed'
  push:
    branches:
      - 'helm'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: tag check
        run: |
          GIT_SHA="$(echo ${{ github.sha }} | cut -c1-7)"
          INP_SHA="${{ github.sha }}"
          echo "TAG=${INP_SHA:-$GIT_SHA}" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ env.TAG }}
      - name: kubectl
        uses: azure/setup-kubectl@v3
      - name: helm
        uses: azure/setup-helm@v3
      - name: kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: deploy
        run: |
          helm upgrade --install service ./helm \
            --namespace dev \
            --set image.tag=${{ env.TAG }}
            --wait